# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/facultate/an2sem2/psn/proiect_masina/proiect_masina.cache/wt [current_project]
set_property parent.project_path D:/facultate/an2sem2/psn/proiect_masina/proiect_masina.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/facultate/an2sem2/psn/proiect_masina/proiect_masina.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/facultate/an2sem2/psn/proiect_masina/proiect_masina.srcs/sources_1/new/count9_0.vhd
  D:/facultate/an2sem2/psn/proiect_masina/proiect_masina.srcs/sources_1/new/count5_0.vhd
  D:/facultate/an2sem2/psn/proiect_masina/proiect_masina.srcs/sources_1/new/div_frecv_2min.vhd
  D:/facultate/an2sem2/psn/proiect_masina/proiect_masina.srcs/sources_1/new/timer_usa.vhd
  D:/facultate/an2sem2/psn/proiect_masina/proiect_masina.srcs/sources_1/new/Sumator_Timp.vhd
  D:/facultate/an2sem2/psn/proiect_masina/proiect_masina.srcs/sources_1/new/timer_ssd.vhd
  D:/facultate/an2sem2/psn/proiect_masina/proiect_masina.srcs/sources_1/new/SSD.vhd
  D:/facultate/an2sem2/psn/proiect_masina/proiect_masina.srcs/sources_1/new/MPG.vhd
  D:/facultate/an2sem2/psn/proiect_masina/proiect_masina.srcs/sources_1/new/div_frecv1sec.vhd
  D:/facultate/an2sem2/psn/proiect_masina/proiect_masina.srcs/sources_1/new/div_frecv1min.vhd
  D:/facultate/an2sem2/psn/proiect_masina/proiect_masina.srcs/sources_1/new/Main.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/facultate/an2sem2/AC/lab1_numarator/Basys3_test_env.xdc
set_property used_in_implementation false [get_files D:/facultate/an2sem2/AC/lab1_numarator/Basys3_test_env.xdc]


synth_design -top main -part xc7a35tcpg236-1


write_checkpoint -force -noxdef main.dcp

catch { report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb }
